

#ifndef _ADC_CONFIG_H
#define _ADC_CONFIG_H



#define SELECTED_CHANNEL      CHANNEL_0

#define SCAN_MODE             DISABLE_SCAN_MODE

#define DATA_ALIGENMENT       RIGHT_ALIGNMENT

#define CONVERSION_MODE       CONTINOUS_CONVERSION

#define SAMPLING_TIME         SAMPLING_TIME_1_5

#define NUMBER_CONVERSION     NUM_CONVERSION_0


#endif
